---
- name: Uninstall existing ssh key(s)
  hosts: all

  vars:
    - public_keys:
      - ~/.ssh/id_rsa.pub
      - ~/.ssh/ansible_id_rsa.pub
    - operation: remove
  roles:
    - role: ../../roles/maintenance.ops/key.ops/
