---
- name: Install Nerdctl with official script, if not present
  block: 
    - name: Check if Nerdctl is installed
      shell: "command -v nerdctl"
      register: is_nerdctl_installed
      changed_when: false
      failed_when: is_nerdctl_installed.stdout | length == 0
  rescue:
    - name: Install Nerdctl with official script
      shell: "curl -sSL https://github.com/containerd/nerdctl/releases/download/v{{ nerdctl_version }}/nerdctl-{{ nerdctl_version }}-linux-amd64.tar.gz | sudo tar -C -xzvvf /usr/local/bin"

