---
- name: Rootless User
  block:
    - name: Check if the rootless user exists
      shell: grep "^{{ rootless_user }}:" /etc/passwd
      register: is_rootless_user_exist
      changed_when: false
      failed_when: rootless_user not in is_rootless_user_exist.stdout

  rescue:
    - name: Create the default rootless user and add it to the sudo group
      ansible.builtin.user:
        name: "{{ rootless_user }}"
        shell: /bin/bash
        groups: sudo
        createhome: yes
        state: present

