---
- name: Disable password login
  ansible.builtin.lineinfile: 
    dest: "/etc/ssh/sshd_config" 
    regexp: '^(#\s*)?PasswordAuthentication '
    line: 'PasswordAuthentication no'

- name: Restart openssh server
  ansible.builtin.service: 
    name: ssh
    state: restarted
