---
- name: Backup data to minio bucket
  command: "/home/{{ ansible_user }}/backup.sh"
  register: result

- name: Check if backup job has completed successfully
  ansible.builtin.debug:
    msg: "Backup ran successfully!"
  when: result.rc == 0
