---
- name: Update apt source
  ansible.builtin.copy:
    dest: "/etc/apt/sources.list"
    content: |
      # Primary
      deb {{ primary_source_uri }} {{ release }} main contrib non-free non-free-firmware

      # Primary Updates
      deb {{ primary_source_uri }} {{ release }}-updates main contrib non-free non-free-firmware
      deb http://mirrors.ustc.edu.cn/debian stable-updates main contrib non-free non-free-firmware

      # Security Patches
      deb {{ security_source_uri }}-security {{ release }}-security main contrib non-free non-free-firmware
